### PR TITLE
Add salt to Finterprinters

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-NikIrgHEKeoLzwEvoso:bngowau) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
> ```cpp
> 
>  public:
>   explicit Sha256Fingerprinter(absl::string_view salt = "") {
> ```

Shouldn't the constructor be private if you want to force callers to use the factories?
___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIpCA7kiEDLNm0M7r:-NikIpCA7kiEDLNm0M7s:bzaxxxp) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L79)):*
> ```cpp
> }
> 
> Fingerprinter* GetSaltedSha256Fingerprinter(absl::string_view salt) {
> ```

Return an std::unique_ptr rather than  raw pointer to show that ownership is being passed to the caller.



_Code quote:_
```cpp
Fingerprinter*
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-NikKDYk7LjBD88IDqm1:bns8gak) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't the constructor be private if you want to force callers to use the factories?
</blockquote></details>

As factory functions needs to call the constructor, I cannot make them private. 
This class `Sha256Fingerprinter` is only in .cc file, so it will not be called by users.
___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIpCA7kiEDLNm0M7r:-NikKCvHCsAovAO14CAN:bu4ozqt) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Return an std::unique_ptr rather than  raw pointer to show that ownership is being passed to the caller.
</blockquote></details>

Done.
Thanks!

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-NikTXe7DEMKIXHh1gYq:bm61k3q) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
> As factory functions needs to call the constructor, I cannot make them private.

https://abseil.io/tips/134

> This class `Sha256Fingerprinter` is only in .cc file, so it will not be called by users.

This isn't true. The class declaration is right here in the header file. Also putting things in the source file doesn't on its own imply privacy.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-Nik_JeRAR-0sU_jjwKF:b59pz3u) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> As factory functions needs to call the constructor, I cannot make them private.

https://abseil.io/tips/134

> This class `Sha256Fingerprinter` is only in .cc file, so it will not be called by users.

This isn't true. The class declaration is right here in the header file. Also putting things in the source file doesn't on its own imply privacy.
</blockquote></details>

I see the point. 
However functions like `GetSaltedSha256Fingerprinter` is not `Fingerprinter::GetSaltedSha256Fingerprinter` so they do not have access to the private constructor. 
If I understanding correctly, the keyword `new` can access private constructor only in the context of `Fingerprinter::`. Do you see any workaround?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-NikwqPUAzvoaA6OzKIE:b-t9wmpf) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
> This isn't true. The class declaration is right here in the header file. Also putting things in the source file doesn't on its own imply privacy.

Oops, I misread. Fingerprinter is indeed defined in the header, but not Sha256Fingerprinter. Is there a reason for this? Given that the caller is fully aware of the implementation by name, why not just make the classes themselves public?

> If I understanding correctly, the keyword `new` can access private constructor only in the context of `Fingerprinter::`. Do you see any workaround?

My understanding is that you have the factories so that you can maintain singleton instances of the non-salted versions. How important is that? If not, then my suggestion would be to just make the constructors public and drop the factories. If you want to enforce the factories, then have them be static members of their respective types.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-Nil9Dy834PP-Nn8DTLr:b-g7n94g) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> This isn't true. The class declaration is right here in the header file. Also putting things in the source file doesn't on its own imply privacy.

Oops, I misread. Fingerprinter is indeed defined in the header, but not Sha256Fingerprinter. Is there a reason for this? Given that the caller is fully aware of the implementation by name, why not just make the classes themselves public?

> If I understanding correctly, the keyword `new` can access private constructor only in the context of `Fingerprinter::`. Do you see any workaround?

My understanding is that you have the factories so that you can maintain singleton instances of the non-salted versions. How important is that? If not, then my suggestion would be to just make the constructors public and drop the factories. If you want to enforce the factories, then have them be static members of their respective types.
</blockquote></details>

Other classes of `any-sketch` are also following this pattern: hide the derived class in .cc and leave the factory functions in header file.
Do you think it is a good idea to keep the repo consistent?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/cc/common_cpp/fingerprinters/fingerprinters.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-NikIrgHEKeoLzwEvosn:-NilcXLZ86vboFTmOdNc:b-k3ogcw) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/f798718265221ad1af884cb50683f77c23e04711/src/main/cc/common_cpp/fingerprinters/fingerprinters.cc#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Other classes of `any-sketch` are also following this pattern: hide the derived class in .cc and leave the factory functions in header file.
Do you think it is a good idea to keep the repo consistent?
</blockquote></details>

Ah, if it's a common pattern then I guess it's fine. It's not a huge deal.

**Review by ple13 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by stevenwarejones — COMMENTED** [review]
This should probably get combined with the PepperedFingerprinter - https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4e70562838200c34489699811c7d4f698f8a457/src/main/cc/wfa/panelmatch/common/crypto/peppered_fingerprinter.cc#L32

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/38#-:-Nippbld7Ujli1Ht88C0:b-moyn29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by renjiezh** [comment]
> This should probably get combined with the PepperedFingerprinter - https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f4e70562838200c34489699811c7d4f698f8a457/src/main/cc/wfa/panelmatch/common/crypto/peppered_fingerprinter.cc#L32

Thanks steven. This is a very good found.
According to the usage, PepperedFingerprinter can be replaced by Sha256Fingerprinter with salt. I will add a TODO to mark this.

**Comment by renjiezh** [comment]
Hi @stevenwarejones , could you please give an approval for this PR. Appreciate it!

**Pull request merged**
