### PR TITLE
Depend on rules_proto explicitly.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)

### CODE REVIEW

**Review by iverson52000 — COMMENTED** [review]
My PR(https://github.com/world-federation-of-advertisers/common-cpp/pull/29) would depend on this. I am still waiting for Eli to come back to review one more change

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30#-:-N2D43yuEQu4UKifRouH:b-xrtn62)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`build/com_google_private_join_and_compute/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30#-N2D4RkuD0IpN3M16QoB:-N2D4RkuD0IpN3M16QoC:b-kw7y67) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/00986e86b5270b5cb9133f29412f189d9da75048/build/com_google_private_join_and_compute/repo.bzl#L26)):*
> ```Starlark
> 
> def com_google_private_join_and_compute():
>     maybe(
> ```

Is maybe() a better pattern than native.existing_rules()? native.existing_rules() is more common in other code bases from what I saw



_Code quote:_
```Starlark
if "com_google_private_join_and_compute" not in native.existing_rules():
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`build/com_google_private_join_and_compute/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30#-N2D4RkuD0IpN3M16QoB:-N2DZ1fCEC0b3SCnSJrG:b-89g1yf) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/00986e86b5270b5cb9133f29412f189d9da75048/build/com_google_private_join_and_compute/repo.bzl#L26)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Is maybe() a better pattern than native.existing_rules()? native.existing_rules() is more common in other code bases from what I saw
</blockquote></details>

`maybe` is also reasonably frequently used in other repos given that it comes with Bazel. It avoids having to repeat the target name.

**Review by iverson52000 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`.bazelversion` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30#-N2N_004AHc-VfycGzAP:-N2Negkp42V5cQOKoLxE:bbuwpb6) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/28b8830aa72aee3595ebb65b941ebb027afcdac8/.bazelversion#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't you go ahead and put 5.1.1 here?
</blockquote></details>

I just merged my PR to upgrade to 5.1.1 this morning. Sanjay can just merge in the changes

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @iverson52000 and @stevenwarejones)

___
*[`.bazelversion` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30#-N2N_004AHc-VfycGzAP:-N2O-B_f1EDScAOaWM5q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/28b8830aa72aee3595ebb65b941ebb027afcdac8/.bazelversion#L1)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

I just merged my PR to upgrade to 5.1.1 this morning. Sanjay can just merge in the changes
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
