### PR TITLE
Update the release of GoogleTest.

### PR DESCRIPTION
**Pull request by tcsnfkx**
FieldsAre matcher was added in 1.11.0, which is needed in our tests.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, and @my2457)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @tcsnfkx)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20#-MhPButX9nkehKvsBOuk:-MhPButY1KnPHMT0j-AA:b-y3wk3a) (no related file):*
While you're doing this, can you also do these two things?

1. Upgrade `@com_google_protobuf` to match `common-jvm`: https://github.com/world-federation-of-advertisers/common-cpp/issues/19 
2. Rename `@googletest`: https://github.com/world-federation-of-advertisers/common-cpp/issues/13

---

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20#-MhPButX9nkehKvsBOuk:-MhPTFxPEL-o0FqOhs5A:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

While you're doing this, can you also do these two things?

1. Upgrade `@com_google_protobuf` to match `common-jvm`: https://github.com/world-federation-of-advertisers/common-cpp/issues/19 
2. Rename `@googletest`: https://github.com/world-federation-of-advertisers/common-cpp/issues/13
</blockquote></details>

Done.

---

**Review by efoxepstein — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, and @my2457)

**Pull request merged**
