### PR TITLE
Load protobuf repo and provide protobuf matchers in common-cpp.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wliue)

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx)

___
*[build/com_google_protobuf/BUILD.bazel, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15#-MfoGk9u9Z7mzgySrueD:-MfoGk9u9Z7mzgySrueE:bta8hi0) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/05b40d05339da34c1ee1a20a9d963a3ebc6c8525/build/com_google_protobuf/BUILD.bazel#L0)):*
Is this intentionally blank?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: all files reviewed, 1 unresolved discussion (waiting on @wliue)

___
*[build/com_google_protobuf/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15#-MfoGk9u9Z7mzgySrueD:-MfoHnpK1OwSgDYcB2Dr:b-x7omwz) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/05b40d05339da34c1ee1a20a9d963a3ebc6c8525/build/com_google_protobuf/BUILD.bazel#L)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is this intentionally blank?
</blockquote></details>

Yes -- it's required to have a `BUILD.bazel` file in directories with `.bzl` files.

**Review by wliue — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: all files reviewed, 1 unresolved discussion (waiting on @wliue)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: all files reviewed, 1 unresolved discussion (waiting on @wliue)

___
*[build/com_google_protobuf/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15#-MfoGk9u9Z7mzgySrueD:-MfoTfGP8XCGClsbtgEi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/05b40d05339da34c1ee1a20a9d963a3ebc6c8525/build/com_google_protobuf/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes -- it's required to have a `BUILD.bazel` file in directories with `.bzl` files.
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24)

**Review by mpatel24 — APPROVED** [review]

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tcsnfkx)

___
*[build/deps_step_1.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15#-Mg6k2zZAKOXRBHIjLWl:-Mg6k2zZAKOXRBHIjLWm:b-f8pt0c) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/05b40d05339da34c1ee1a20a9d963a3ebc6c8525/build/deps_step_1.bzl#L27)):*
> ```Starlark
> load("//build/com_google_private_join_and_compute:repo.bzl", "com_google_private_join_and_compute_repo")
> 
> def common_cpp_deps_step_1():
> ```

In https://github.com/world-federation-of-advertisers/common-jvm/pull/20, @sanjayvas asked Erin to switch from `foo_step_X()` to `foo_repositories()`, `foo_deps()`, and `foo_extra_deps()` (if needed). See https://github.com/world-federation-of-advertisers/common-jvm/pull/20#pullrequestreview-719413897.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @wliue)

___
*[build/deps_step_1.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15#-Mg6k2zZAKOXRBHIjLWl:-Mg79_sg3OwOmBabgzBp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/05b40d05339da34c1ee1a20a9d963a3ebc6c8525/build/deps_step_1.bzl#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In https://github.com/world-federation-of-advertisers/common-jvm/pull/20, @sanjayvas asked Erin to switch from `foo_step_X()` to `foo_repositories()`, `foo_deps()`, and `foo_extra_deps()` (if needed). See https://github.com/world-federation-of-advertisers/common-jvm/pull/20#pullrequestreview-719413897.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
