### PR TITLE
Update Bazel version to 5.1.1

### PR DESCRIPTION
**Pull request by iverson52000**
Add .bazelversion file, update Bazel version to 5.1.1, and fix breaking changes from transitive dependencies
image

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @iverson52000, @jonmolle, and @tcsnfkx)

___
*[`.gitignore` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1KdM4KBzssA2iFYuTZ:-N1KdM4KBzssA2iFYuT_:bdh16gk) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/.gitignore#L13)):*
> ```ignore
> 
> # ClangFormat.
> /.clang-format
> ```

nit: not an issue to leave this here, but we shouldn't need any exceptions to clang-format AFAIK. We just use `-- style=Google` AFAIK



_Code quote:_
```ignore
# ClangFormat.
/.clang-format
```
___
*[`build/com_github_grpc_grpc/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1KdhKO5vWzpqUbbo6T:-N1KdhKO5vWzpqUbbo6U:b-9lrymp) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/build/com_github_grpc_grpc/repo.bzl#L26)):*
> ```Starlark
>             name = "com_github_grpc_grpc",
>             sha256 = "e18b16f7976aab9a36c14c38180f042bb0fd196b75c9fd6a20a2b5f934876ad6",
>             strip_prefix = "grpc-1.45.2",
> ```

nit: `1.46.0` just got released yesterday :)



_Code quote:_
```Starlark
1.45.2
```
___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1Kds0a84tQHwSruTw8:-N1Kds0a84tQHwSruTw9:b-jnrc7u) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/src/main/cc/common_cpp/testing/status_matchers.h#L29)):*
> ```objc
> MATCHER(IsOk, "") {
>   if (!arg.ok()) {
>     // *result_listener << "expected OK status but got: " << arg;
> ```

Why are these commented-out?



_Code quote:_
```objc
 // *result_listener << "expected OK status but got: " << arg;
```

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @iverson52000, @jonmolle, @SanjayVas, and @tcsnfkx)

___
*[`.gitignore` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1KdM4KBzssA2iFYuTZ:-N1Kntbp2vHD9-UugXT9:b-c6l10r) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/.gitignore#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: not an issue to leave this here, but we shouldn't need any exceptions to clang-format AFAIK. We just use `-- style=Google` AFAIK
</blockquote></details>

What IDE should we use for C++ codebase? I installed Clion and to specify the coding style in ClangFormat, it will create a .clang-format file?

___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1Kds0a84tQHwSruTw8:-N1KmyWs3U7t2_Dl2hcj:b4hsbiy) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/src/main/cc/common_cpp/testing/status_matchers.h#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why are these commented-out?
</blockquote></details>

When I try to run unit tests in any-sketch repo, I got error thrown from calling this file at this line. The error message is attached below. I am not very familiar with C++ yet so not sure what to change. @efoxepstein I saw you added the code. Do you mind taking a look? Thanks!

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @jonmolle, @SanjayVas, and @tcsnfkx)

___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1Kds0a84tQHwSruTw8:-N1LIY298RARParJJW1Y:bl6obdv) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/src/main/cc/common_cpp/testing/status_matchers.h#L29)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

When I try to run unit tests in any-sketch repo, I got error thrown from calling this file at this line. The error message is attached below. I am not very familiar with C++ yet so not sure what to change. @efoxepstein I saw you added the code. Do you mind taking a look? Thanks!


</blockquote></details>

Try something like this:

```
absl::Status GetStatus(const absl::Status& status) { return status; }

template <class T>
absl::Status GetStatus(const absl::StatusOr<T>& status) { return status.status(); }

*result_listener << "expected OK status but code: " << GetStatus(arg);
```

Seems like the underlying issue is that `IsOk` and friends are being using on `absl::StatusOr` instead of `absl::Status`.

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @jonmolle, @SanjayVas, and @tcsnfkx)

___
*[`build/com_github_grpc_grpc/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1KdhKO5vWzpqUbbo6T:-N1iqAbsDs8-SVXnJcfH:b-bu91xm) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/build/com_github_grpc_grpc/repo.bzl#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `1.46.0` just got released yesterday :)
</blockquote></details>

Updated
___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1Kds0a84tQHwSruTw8:-N1inGuiAsw-5imG_8se:b-rspxq8) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/46e3dfef675ea4b1c7bd0bf5fb62328615d1f54d/src/main/cc/common_cpp/testing/status_matchers.h#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Try something like this:

```
absl::Status GetStatus(const absl::Status& status) { return status; }

template <class T>
absl::Status GetStatus(const absl::StatusOr<T>& status) { return status.status(); }

*result_listener << "expected OK status but code: " << GetStatus(arg);
```

Seems like the underlying issue is that `IsOk` and friends are being using on `absl::StatusOr` instead of `absl::Status`.
</blockquote></details>

@efoxepstein It works. Thanks a lot!

**Review by efoxepstein — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @iverson52000, @jonmolle, and @tcsnfkx)

___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1jz3zJ89eaJRAdmio3:-N1jz3zJ89eaJRAdmio4:b2q5bmp) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/4adf376fd7365d41e5573f548ea94c075675f1d6/src/main/cc/common_cpp/testing/status_matchers.h#L26)):*
> ```objc
> 
> namespace wfa {
> absl::Status GetStatus(const absl::Status& status) { return status; }
> ```

Please make sure that this doesn't violate the ODR. Mark as inline or move definition into a CC file please.
___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1jzee32J0Wn2rS3NFR:-N1jzee32J0Wn2rS3NFS:b-ati443) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/4adf376fd7365d41e5573f548ea94c075675f1d6/src/main/cc/common_cpp/testing/status_matchers.h#L26)):*
> ```objc
> 
> namespace wfa {
> absl::Status GetStatus(const absl::Status& status) { return status; }
> ```

Please move into a nested namespace called internal

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @iverson52000, @jonmolle, @SanjayVas, and @tcsnfkx)

___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1jz3zJ89eaJRAdmio3:-N2N01ieE5eObBCiMfqZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/4adf376fd7365d41e5573f548ea94c075675f1d6/src/main/cc/common_cpp/testing/status_matchers.h#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please make sure that this doesn't violate the ODR. Mark as inline or move definition into a CC file please.
</blockquote></details>

Done.
___
*[`src/main/cc/common_cpp/testing/status_matchers.h` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29#-N1jzee32J0Wn2rS3NFR:-N2N02ID-d480U0FBYpG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-cpp/blob/4adf376fd7365d41e5573f548ea94c075675f1d6/src/main/cc/common_cpp/testing/status_matchers.h#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please move into a nested namespace called internal 
</blockquote></details>

Done.

**Review by iverson52000 — COMMENTED** [review]
> Dismissed @efoxepstein from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-cpp/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein, @jonmolle, and @tcsnfkx)

**Pull request merged**
